all:	run

run:	server.o client1.o client2.o client3.o client4.o

server.o:	server4.c
		gcc server4.c -o s

client1.o:	client4.c
		gcc client4.c -o c1

client2.o:	client4.c
		gcc client4.c -o c2

client3.o:	client4.c
		gcc client4.c -o c3

client4.o:	client4.c
		gcc client4.c -o c4


	
