run:
	python3 Query1/mapper.py | sort | python3 Query1/reducer.py
	echo "Completed Query 1"
	python3 Query2/mapper.py | sort | python3 Query2/reducer.py
	echo "Completed Query 2"
	python3 Query3/mapper.py | sort | python3 Query3/reducer.py
	echo "Completed Query 3"
	python3 Query4/mapper.py | sort | python3 Query4/reducer.py
	echo "Completed Query 4"
	python3 Query5/mapper.py | sort | python3 Query5/reducer.py
	echo "Completed Query 5"
